export const tokens = {
  color: {
    transparent: 'transparent',
    white: '#FFFFFF',
    black: '#000000',
    blue05: '#F1F4FC',
    blue10: '#DDE5F7',
    blue20: '#BBCBF0',
    blue30: '#96B2F2',
    blue40: '#2953B2',
    blue50: '#20408C',
    blue60: '#172F66',
    lightBlue05: '#EDF5FB',
    lightBlue10: '#DEECF7',
    lightBlue20: '#B9DAF3',
    lightBlue30: '#7CBBEA',
    lightBlue40: '#2978B5',
    lightBlue50: '#216090',
    lightBlue60: '#143C5C',
    red05: '#FBF2F2',
    red10: '#F8E3E3',
    red20: '#EDBABA',
    red30: '#F49494',
    red40: '#CC3D3D',
    red50: '#962828',
    red60: '#782020',
    green05: '#ECF7EC',
    green10: '#DFF1E0',
    green20: '#AEDDB0',
    green30: '#83D187',
    green40: '#38853C',
    green50: '#285F2B',
    green60: '#1C431E',
    orange05: '#FFF5EC',
    orange10: '#FFEBD7',
    orange20: '#FFCD9B',
    orange30: '#F5AE70',
    orange40: '#D56A00',
    orange50: '#A65200',
    orange60: '#5C2C00',
    cyan05: '#EFF9FB',
    cyan10: '#D5EFF4',
    cyan20: '#A4DEE9',
    cyan30: '#63CBDB',
    cyan40: '#1C99A8',
    cyan50: '#207883',
    cyan60: '#093F46',
    purple05: '#F6F3FA',
    purple10: '#EDE8F4',
    purple20: '#D3C4E4',
    purple30: '#C6A5EA',
    purple40: '#835AB3',
    purple50: '#684391',
    purple60: '#462D63',
    pink05: '#FBF2F5',
    pink10: '#F5E0E7',
    pink20: '#EAB2C4',
    pink30: '#F48AAB',
    pink40: '#DA3561',
    pink50: '#B1204B',
    pink60: '#850D35',
    teal05: '#E8F7F3',
    teal10: '#CDEFE7',
    teal20: '#A6E0D2',
    teal30: '#66CBB7',
    teal40: '#007969',
    teal50: '#006053',
    teal60: '#00463C',
    gray05: '#F4F4F4',
    gray10: '#E6E6E6',
    gray20: '#DDDDDD',
    gray30: '#B9B9B9',
    gray40: '#747474',
    gray50: '#545454',
    gray60: '#3B3B3B',
    grayTransparent05: 'rgba(0, 0, 0, 0.05)',
    grayTransparent10: 'rgba(0, 0, 0, 0.1)',
    grayTransparent20: 'rgba(0, 0, 0, 0.2)',
    grayTransparent30: 'rgba(0, 0, 0, 0.3)',
    grayTransparent40: 'rgba(0, 0, 0, 0.4)',
    grayTransparent50: 'rgba(0, 0, 0, 0.5)',
    grayTransparent60: 'rgba(0, 0, 0, 0.6)',
    grayTransparent70: 'rgba(0, 0, 0, 0.7)',
    grayTransparent80: 'rgba(0, 0, 0, 0.8)',
    grayTransparent90: 'rgba(0, 0, 0, 0.9)',
  },
  bg: {
    primary: '$color-white',
    secondary: '$color-gray05',
    disabled: '$color-gray10',
    positive: '$color-green10',
    critical: '$color-red10',
    warning: '$color-orange10',
    info: '$color-lightBlue10',
    inverted: '$color-black',
    overlay: '$color-grayTransparent50',
    skeleton: 'linear-gradient(90deg, transparent, $color-gray10, transparent)',
    action: {
      neutral: {
        secondary: {
          '*': '$color-gray05',
          hover: '$color-gray10',
          pressed: '$color-gray20',
        },
        tertiary: {
          '*': 'transparent',
          hover: '$color-grayTransparent05',
          pressed: '$color-grayTransparent10',
        },
      },
      main: {
        primary: {
          '*': '$color-blue40',
          hover: '$color-blue50',
          pressed: '$color-blue60',
        },
        secondary: {
          '*': '$color-blue10',
          hover: '$color-blue20',
          pressed: '$color-blue30',
        },
        tertiary: {
          '*': 'transparent',
          hover: '$color-blue05',
          pressed: '$color-blue10',
          selected: '$color-blue05',
        },
      },
      critical: {
        primary: {
          '*': '$color-red40',
          hover: '$color-red50',
          pressed: '$color-red60',
        },
        secondary: {
          '*': '$color-red10',
          hover: '$color-red20',
          pressed: '$color-red30',
        },
        tertiary: {
          '*': 'transparent',
          hover: '$color-red05',
          pressed: '$color-red10',
          selected: '$color-red05',
        },
      },
    },
    form: {
      neutral: {
        '*': 'transparent',
        hover: '$color-gray10',
        pressed: '$color-gray30',
        checked: {
          '*': '$color-black',
          hover: '$color-gray60',
          pressed: '$color-gray50',
        },
        inactive: {
          '*': '$color-gray30',
          hover: '$color-gray50',
          pressed: '$color-gray60',
        },
        active: {
          '*': '$color-black',
          hover: '$color-gray60',
          pressed: '$color-gray50',
        },
      },
      control: {
        hover: 'transparent',
        checked: {
          '*': '$color-blue40',
          hover: '$color-blue50',
          focus: '$color-blue50',
        },
        active: {
          '*': '$color-green40',
          hover: '$color-green50',
        },
        inactive: {
          '*': '$color-gray30',
          hover: '$color-gray40',
        },
      },
    },
  },
  fg: {
    primary: '$color-black',
    secondary: '$color-gray50',
    disabled: '$color-gray40',
    inverted: '$color-white',
    positive: '$color-green40',
    info: '$color-lightBlue40',
    critical: '$color-red40',
    warning: '$color-orange40',
    action: {
      neutral: {
        tertiary: {
          '*': '$color-gray50',
          hover: '$color-gray60',
          pressed: '$color-black',
        },
      },
      main: {
        primary: {
          '*': '$color-white',
          hover: '$color-white',
          pressed: '$color-white',
        },

        secondary: {
          '*': '$color-blue40',
          hover: '$color-blue50',
          pressed: '$color-blue60',
        },

        tertiary: {
          '*': '$color-blue40',
          hover: '$color-blue50',
          pressed: '$color-blue60',
          selected: '$color-blue40',
        },
      },
      critical: {
        primary: {
          '*': '$color-white',
          hover: '$color-white',
          packageressed: '$color-white',
        },

        secondary: {
          '*': '$color-red40',
          hover: '$color-red50',
          pressed: '$color-red60',
        },

        tertiary: {
          '*': '$color-red40',
          hover: '$color-red50',
          pressed: '$color-red60',
          selected: '$color-red40',
        },
      },
    },
    form: {
      neutral: {
        '*': '$color-black',
        checked: '$color-white',
      },
      control: {
        '*': '$color-white',
        neutral: '$color-black',
        checked: '$color-white',
      },
    },
  },
}
