import type { StyleObject } from '@vtex/admin-ui'

export default {
  wrapper: {
    overflow: 'visible',
    marginY: 5,
    border: 'default',
  },
  preview: {
    padding: 5,
    position: 'relative',
    color: 'base',
    bg: 'base',
    minHeight: 'auto',
    borderRadius: 'default',
    fontFamily: 'mono',
  },
  editorWrapper: {
    borderBottomLeftRadius: 'default',
    borderBottomRightRadius: 'default',
    fontFamily: 'mono',
    overflow: 'auto',
    position: 'relative',
    'textarea, pre': {
      fontSize: '14px !important',
      lineHeight: '22px !important',
    },
    '* > textarea:focus': { outline: 'none' },
    '.token': { fontStyle: 'normal !important' },
  },
  liveEditor: {
    display: 'block',
    whiteSpace: 'pre-wrap',
    textAlign: 'left',
    fontFamily: 'mono',
    padding: '1rem',
    bg: 'notification.critical',
    color: 'notification.critical',
    text: 'body',
  },
  copyButton: {
    position: 'absolute',
    top: '18px',
    right: '6px',
    zIndex: 1,
  },
  preHeader: {
    fontSize: '12px',
    lineHeight: '18px',
    marginTop: '0.5rem',
    padding: '0.8rem 1rem',
    borderRadius: '5px 5px 0 0',
  },
  lineNo: {
    display: 'inline-block',
    width: '2rem',
    userSelect: 'none',
    opacity: 0.3,
  },
  pre: {
    fontFamily: 'mono',
    WebkitOverflowScrolling: 'touch',
    overflowWrap: 'break-word',
    code: {
      cssFloat: 'left',
      minWidth: '100%',
      paddingRight: '1rem',
    },
    '.token-line': {
      lineHeight: '22px',
      fontSize: '14px',
      minWidth: '100%',
    },
    '.highlight-line': {
      bg: 'hightlight',
      marginLeft: '-1rem',
      marginRight: '-2rem',
      padding: '0 0.75rem',
      borderLeft: '4px solid blue',
    },
    overflow: 'auto',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    textAlign: 'left',
  },
} as Record<string, StyleObject>
