apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shoreline
  description: VTEX Design System for back-office experiences.
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex/shoreline
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: GDD93V8D
    vtex.com/sdd-check-skip: 'true'
    vtex.com/sdd-check-skip-reason: Shoreline is a public repository, so the specs shouldn't live there. Because of that we've created Shoreline Specs repository (https://github.com/vtex/shoreline-specs) with the Spec Kit setup
spec:
  system: admin
  lifecycle: stable
  owner: te-0009
  type: library
