/* eslint-disable no-await-in-loop */
import { readFileSync } from 'fs'
import { generateComponents } from './handlers'
import { ProjectParser } from 'typedoc-json-parser'
import type { PkgToBeDocumentedPaths } from './config'
import { tmpDocsJsonPath } from './config'

/**
 * Parse the JSON docs generated by typedoc and generate the docs for the
 * components using the json-parser and handlebars.
 */
export async function parseJSONDocs(paths: PkgToBeDocumentedPaths) {
  const data = JSON.parse(readFileSync(tmpDocsJsonPath, 'utf8'))
  const project = new ProjectParser({ data })

  if (paths.components?.docPath && paths.components?.filename) {
    await generateComponents(project, paths.components)
  }
}
