/* eslint-disable no-await-in-loop */
import { generateComponents } from './handlers'
import type { ConfigPaths } from './config'
import type {
  FunctionParser,
  InterfaceParser,
  TypeAliasParser,
} from 'typedoc-json-parser'

/**
 * Parse the JSON docs generated by typedoc and generate the docs for the
 * components using the json-parser and handlebars.
 */
export async function parseJSONDocs(
  functions: FunctionParser[],
  interfaces: InterfaceParser[],
  typeAliases: TypeAliasParser[],
  paths: ConfigPaths
) {
  if (paths.components?.docPath && paths.components?.filename) {
    await generateComponents(
      functions,
      interfaces,
      typeAliases,
      paths.components
    )
  }
}
