/* eslint-disable no-await-in-loop */
import { readFileSync } from 'fs'
import { generateComponent, generateMetaJSON } from './handlers'
import { isComponent } from './strings'
import { ProjectParser } from 'typedoc-json-parser'

/**
 * Parse the JSON docs generated by typedoc and generate the docs for the
 * components using the json-parser and handlebars.
 */
export async function parseJSONDocs() {
  const data = JSON.parse(readFileSync('./documentation.json', 'utf8'))
  const project = new ProjectParser({ data })

  for (const func of project.functions) {
    if (isComponent(func.name)) {
      await generateComponent(project, func)
    }

    await generateMetaJSON(project)
  }
}
