export default {
  index: { title: 'All Components', theme: { layout: 'full' } },
  alert: 'Alert',
  button: 'Button',
  checkbox: 'Checkbox',
  collection: 'Collection',
  'confirmation-modal': 'ConfirmationModal',
  'contextual-help': 'ContextualHelp',
  divider: 'Divider',
  drawer: 'Drawer',
  'empty-state': 'EmptyState',
  field: 'Field',
  filter: 'Filter',
  heading: 'Heading',
  'icon-button': 'IconButton',
  input: 'Input',
  label: 'Label',
  link: 'Link',
  menu: 'Menu',
  modal: 'Modal',
  page: 'Page',
  pagination: 'Pagination',
  popover: 'Popover',
  radio: 'Radio',
  search: 'Search',
  select: 'Select',
  skeleton: 'Skeleton',
  spinner: 'Spinner',
  tab: 'Tab',
  table: 'Table',
  tag: 'Tag',
  text: 'Text',
  textarea: 'Textarea',
  toast: 'Toast',
  tooltip: 'Tooltip',

  Charts: { type: 'separator', title: 'Data Visualization' },
  chart: 'Chart',
  bar: 'Bar Chart',
  line: 'Line Chart',
  'chart-compositor': 'Chart Compositor',

  Date: { type: 'separator', title: 'Date' },
  calendar: 'Calendar',
  'date-field': 'DateField',
  'date-picker': 'DatePicker',
  'date-range-picker': 'DateRangePicker',
  'date-segment': 'DateSegment',
  'range-calendar': 'RangeCalendar',
  'time-input': 'TimeInput',

  DataVisualization: { type: 'separator', title: 'Data Visualization' },
  'bar-chart': 'BarChart',

  Primitives: { type: 'separator', title: 'Primitives' },
  'accessible-icon': 'AccessibleIcon',
  clickable: 'Clickable',
  combobox: 'Combobox',
  compose: 'Compose',
  'link-box': 'LinkBox',
  'locale-provider': 'LocaleProvider',
  'visually-hidden': 'VisuallyHidden',

  Layout: { type: 'separator', title: 'Layout' },
  bleed: 'Bleed',
  center: 'Center',
  content: 'Content',
  flex: 'Flex',
  grid: 'Grid',
  stack: 'Stack',
}
