export const theme = {
  space: {
    '0': '0rem',
    '1': '0.0625rem',
    '2': '0.125rem',
    '3': '0.25rem',
    '4': '0.375rem',
    '5': '0.5rem',
    '6': '0.625rem',
    '7': '0.75rem',
    '8': '0.875rem',
    '9': '1rem',
    '10': '1.125rem',
    '11': '1.25rem',
    '12': '1.375rem',
    '13': '1.5rem',
  },
  sizes: {
    '0': '0rem',
    '1': '0.0625rem',
    '2': '0.125rem',
    '3': '0.25rem',
    '4': '0.5rem',
    '5': '0.75rem',
    '6': '1rem',
    '7': '1.25rem',
    '8': '1.5rem',
    '9': '1.75rem',
    '10': '2rem',
    '11': '2.25rem',
    '12': '2.5rem',
    '13': '3rem',
    '14': '4rem',
    '15': '5rem',
    '16': '6rem',
    '17': '8rem',
    '18': '10rem',
    '19': '12rem',
    '20': '14rem',
    '21': '16rem',
    xs: '20rem',
    sm: '24rem',
    md: '28rem',
    lg: '32rem',
    xl: '36rem',
    '2xl': '42rem',
    '3xl': '48rem',
    '4xl': '56rem',
    '5xl': '64rem',
    '6xl': '72rem',
    '1/2': '50%',
    '1/3': '33.333333%',
    '2/3': '66.666667%',
    '1/4': '25%',
    '2/4': '50%',
    '3/4': '75%',
    '1/5': '20%',
    '2/5': '40%',
    '3/5': '60%',
    '4/5': '80%',
    '1/6': '16.666667%',
    '2/6': '33.333333%',
    '3/6': '50%',
    '4/6': '66.666667%',
    '5/6': '83.333333%',
    '1/12': '8.333333%',
    '2/12': '16.666667%',
    '3/12': '25%',
    '4/12': '33.333333%',
    '5/12': '41.666667%',
    '6/12': '50%',
    '7/12': '58.333333%',
    '8/12': '66.666667%',
    '9/12': '75%',
    '10/12': '83.333333%',
    '11/12': '91.666667%',
    full: '100%',
    screenHeight: '100vh',
    screenWidth: '100vw',
  },
  colors: {
    text: '#323845',
    background: '#FFFFFF',
    muted: ['#686E7B', '#8B9299', '#C1C6CC', '#D7DADF', '#F3F5F9'],
    focus: '#8DB6FA',
    primary: {
      base: '#2953B2',
      hover: '#1E4397',
      active: '#3F6FDB',
      contrast: '#FFFFFF',
      washed: '#F4F8FE',
    },
    danger: {
      base: '#D23030',
      hover: '#A70C0C',
      active: '#DE0404',
      contrast: '#FFFFFF',
      washed: '#FFF0F0',
    },
  },
  components: {
    skeleton: {
      styles: {
        display: 'inline-block',
        width: 'full',
        height: 'full',
        backgroundColor: 'muted.4',
        backgroundSize: `200px 100%`,
        backgroundRepeat: 'no-repeat',
        lineHeight: 1,
      },
      shape: {
        rect: {
          borderRadius: 4,
        },
        circle: {
          borderRadius: '100%',
        },
      },
    },
    button: {
      styles: {
        borderWidth: 1,
        borderRadius: 3,
        cursor: 'pointer',
        position: 'relative',
        borderStyle: 'solid',
        '&:focus': {
          outline: 'none',
        },
      },
      size: {
        regular: {
          paddingY: 5,
          fontSize: 1,
          height: 12,
          width: 'auto',
          paddingLeft: 9,
          paddingRight: 9,
        },
        'regular-icon': {
          paddingY: 5,
          fontSize: 1,
          height: 12,
          width: 12,
          paddingLeft: 3,
          paddingRight: 3,
        },
        'regular-icon-start': {
          paddingY: 5,
          fontSize: 1,
          height: 12,
          width: 'auto',
          paddingLeft: 5,
          paddingRight: 7,
        },
        'regular-icon-end': {
          paddingY: 5,
          fontSize: 1,
          height: 12,
          width: 'auto',
          paddingLeft: 7,
          paddingRight: 5,
        },
        small: {
          paddingY: 4,
          fontSize: 0,
          height: 10,
          width: 'auto',
          paddingLeft: 7,
          paddingRight: 7,
        },
        'small-icon': {
          paddingY: 4,
          fontSize: 0,
          height: 10,
          width: 10,
          paddingLeft: 2,
          paddingRight: 2,
        },
        'small-icon-start': {
          paddingY: 4,
          fontSize: 0,
          height: 10,
          width: 'auto',
          paddingLeft: 5,
          paddingRight: 7,
        },
        'small-icon-end': {
          paddingY: 4,
          fontSize: 0,
          height: 10,
          width: 'auto',
          paddingLeft: 7,
          paddingRight: 5,
        },
      },
      variant: {
        'filled-primary': {
          textTransform: 'uppercase',
          color: 'primary.contrast',
          backgroundColor: 'primary.base',
          fontVariationSettings: "'wght' 92",
          borderColor: 'primary.base',
          '&:hover': {
            backgroundColor: 'primary.hover',
            borderColor: 'primary.hover',
          },
          '&:active': {
            backgroundColor: 'primary.active',
            borderColor: 'primary.active',
          },
          '&:disabled': {
            color: 'text',
            borderColor: 'muted.2',
            backgroundColor: 'muted.2',
          },
        },
        'outlined-primary': {
          textTransform: 'uppercase',
          backgroundColor: 'transparent',
          borderColor: 'muted.2',
          color: 'primary.base',
          fontVariationSettings: "'wght' 92",
          '&:hover': {
            backgroundColor: 'primary.washed',
            color: 'primary.hover',
          },
          '&:active': {
            color: 'primary.active',
          },
          '&:disabled': {
            color: 'muted.1',
            backgroundColor: 'muted.4',
          },
        },
        'subtle-primary': {
          borderColor: 'transparent',
          textTransform: 'capitalize',
          backgroundColor: 'transparent',
          color: 'primary.base',
          fontVariationSettings: "'wght' 92",
          '&:hover': {
            color: 'primary.hover',
            backgroundColor: 'primary.washed',
          },
          '&:active': {
            color: 'primary.active',
            backgroundColor: 'primary.washed',
          },
          '&:disabled': {
            color: 'muted.1',
          },
        },
        'filled-danger': {
          textTransform: 'uppercase',
          color: 'danger.contrast',
          backgroundColor: 'danger.base',
          fontVariationSettings: "'wght' 92",
          borderColor: 'danger.base',
          '&:hover': {
            borderColor: 'danger.hover',
            backgroundColor: 'danger.hover',
          },
          '&:active': {
            borderColor: 'danger.active',
            backgroundColor: 'danger.active',
          },
          '&:disabled': {
            borderColor: 'muted.2',
            color: 'text',
            backgroundColor: 'muted.2',
          },
        },
        'outlined-danger': {
          textTransform: 'uppercase',
          backgroundColor: 'transparent',
          borderColor: 'muted.2',
          color: 'danger.base',
          fontVariationSettings: "'wght' 92",
          '&:hover': {
            backgroundColor: 'danger.washed',
            color: 'danger.hover',
          },
          '&:active': {
            color: 'danger.active',
          },
          '&:disabled': {
            color: 'muted.1',
            backgroundColor: 'muted.4',
          },
        },
        'subtle-danger': {
          borderColor: 'transparent',
          textTransform: 'capitalize',
          backgroundColor: 'transparent',
          color: 'danger.base',
          fontVariationSettings: "'wght' 92",
          '&:hover': {
            color: 'danger.hover',
            backgroundColor: 'danger.washed',
          },
          '&:active': {
            color: 'danger.active',
            backgroundColor: 'danger.washed',
          },
          '&:disabled': {
            color: 'muted.1',
          },
        },
      },
    },
    text: {
      variant: {
        small: {
          lineHeight: 'small',
          fontVariationSettings: "'wght' 80",
          fontSize: 0,
        },
        body: {
          lineHeight: 'body',
          fontVariationSettings: "'wght' 80",
          fontSize: 1,
        },
        highlight: {
          lineHeight: 'highlight',
          fontVariationSettings: "'wght' 92",
          fontSize: 1,
        },
        action: {
          lineHeight: 'action',
          fontVariationSettings: "'wght' 92",
          fontSize: 1,
          textTransform: 'uppercase',
        },
        subtitle: {
          lineHeight: 'subtitle',
          fontVariationSettings: "'wght' 92",
          fontSize: 2,
        },
        headline: {
          lineHeight: 'headline',
          fontVariationSettings: "'wght' 92",
          fontSize: 3,
        },
      },
    },
  },
  fontSizes: [12, 14, 16, 20],
  lineHeights: {
    small: 1.125,
    body: 1.25,
    highlight: 1.25,
    action: 1.5,
    subtitle: 1.5,
    headline: 1.5,
  },
  borderWidths: [0, 1, 2, 4, 6],
  borderRadius: [0, 1, 2, 4, 6],
}

export type AdminTheme = typeof theme
