export { useTheme, Theme } from '@vtex-components/theme'
export { ThemeProvider } from './theme'
export { Box, BoxProps } from './components/Box'
export { Button, ButtonProps } from './components/Button'
export { Text, TextProps } from './components/Text'
export { Skeleton, SkeletonProps } from './components/Skeleton'
export { Card, CardProps } from './components/Card'
export * from './icons'
