export const contributors = [
  {
    image: 'https://avatars.githubusercontent.com/u/6964311?v=4',
    username: 'matheusps',
    stats: {
      issues: 13,
      assigns: 9,
      comments: 19,
      pulls: 71,
      reviews: 91,
      merged: 64,
      rate: 44.5,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/33183880?v=4',
    username: 'marcelovicentegc',
    stats: {
      issues: 3,
      assigns: 2,
      comments: 3,
      pulls: 44,
      reviews: 82,
      merged: 42,
      rate: 29.333333333333332,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/20579226?v=4',
    username: 'lucasaarcoverde',
    stats: {
      issues: 2,
      assigns: 3,
      comments: 6,
      pulls: 27,
      reviews: 60,
      merged: 25,
      rate: 20.5,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/84085258?v=4',
    username: 'beatrizmilhomem',
    stats: {
      issues: 10,
      assigns: 1,
      comments: 12,
      pulls: 25,
      reviews: 14,
      merged: 24,
      rate: 14.333333333333334,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/8623116?v=4',
    username: 'anitavincent',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 17,
      reviews: 23,
      merged: 17,
      rate: 9.5,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/8797476?v=4',
    username: 'davicostalf',
    stats: {
      issues: 3,
      assigns: 0,
      comments: 5,
      pulls: 3,
      reviews: 5,
      merged: 3,
      rate: 3.1666666666666665,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/36760180?v=4',
    username: 'lafray',
    stats: {
      issues: 3,
      assigns: 1,
      comments: 3,
      pulls: 1,
      reviews: 0,
      merged: 1,
      rate: 1.5,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/10627086?v=4',
    username: 'emersonlaurentino',
    stats: {
      issues: 1,
      assigns: 0,
      comments: 0,
      pulls: 1,
      reviews: 2,
      merged: 1,
      rate: 0.8333333333333334,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/55562946?v=4',
    username: 'danilomcampos',
    stats: {
      issues: 0,
      assigns: 1,
      comments: 0,
      pulls: 1,
      reviews: 0,
      merged: 1,
      rate: 0.5,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/2573602?v=4',
    username: 'kevinch',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 1,
      reviews: 0,
      merged: 1,
      rate: 0.3333333333333333,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/21042186?v=4',
    username: 'myllenaalves',
    stats: {
      issues: 1,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0.16666666666666666,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/12852518?v=4',
    username: 'vitoria',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/59611647?v=4',
    username: 'JulianaMeyerArruda',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/19390820?v=4',
    username: 'lucasmedeiros',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/77292838?v=4',
    username: 'julia-rabello',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/20714148?v=4',
    username: 'JRobsonJr',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/23522997?v=4',
    username: 'marianabianca',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/31047707?v=4',
    username: 'ingridpitta',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/83723439?v=4',
    username: 'jumeyermattosarruda',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/38146166?v=4',
    username: 'coltran3',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/6525725?v=4',
    username: 'mayzabeel',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/2338593?v=4',
    username: 'carlademarchi',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/32712093?v=4',
    username: 'jardelymaris',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/18720551?v=4',
    username: 'ThaynanAndrey',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/8618687?v=4',
    username: 'gtkatakura',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/7189694?v=4',
    username: 'jonathasbsouza',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/14130609?v=4',
    username: 'RaylaMedeiros',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/8952291?v=4',
    username: 'lbandeira',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/63271570?v=4',
    username: 'joaovictor-local',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/16650877?v=4',
    username: 'luis-f-lins',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/6867958?v=4',
    username: 'thayannevls',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/71647659?v=4',
    username: 'camilavcoutinho',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/23361175?v=4',
    username: 'emerson-paiva',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/11728746?v=4',
    username: 'JoseRenan',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/100872772?v=4',
    username: 'kaio-donadelli',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/26465317?v=4',
    username: 'sheilagomes',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/8990835?v=4',
    username: 'rodrigoimenes',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/136460310?v=4',
    username: 'geisecosta',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/16696167?v=4',
    username: 'JulianaDamurie',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
  {
    image: 'https://avatars.githubusercontent.com/u/5216049?v=4',
    username: 'mairatma',
    stats: {
      issues: 0,
      assigns: 0,
      comments: 0,
      pulls: 0,
      reviews: 0,
      merged: 0,
      rate: 0,
    },
  },
]

export function getContributor(username: string) {
  return contributors.find((contributor) => contributor.username === username)
}
