export { Icon, IconProps } from '@vtex-components/icon'
export { IconWithDirection, IconWithDirectionProps } from './IconWithDirection'
export { IconCancel } from './Cancel'
export { IconCaret } from './Caret'
export { IconCaretBig } from './CaretBig'
export { IconArrow } from './Arrow'
export { IconFavorite } from './Favorite'
export { IconDownload } from './Download'
export { IconLink } from './Link'
export { IconDelete } from './Delete'
export { IconActions } from './Actions'
export { IconTruck } from './Truck'
export { IconMoney } from './Money'
export { IconPrinter } from './Printer'
export { IconClose } from './Close'

// Admin Shell
export { IconAddChannel } from './AddChannel'
export { IconAppStore } from './AppStore'
export { IconOrders } from './Orders'
export { IconCatalog } from './Catalog'
export { IconContent } from './Content'
export { IconDashboard } from './Dashboard'
export { IconHelp } from './Help'
export { IconMarketPlace } from './MarketPlace'
export { IconMarketing } from './Marketing'
export { IconNotifications } from './Notifications'
export { IconSettings } from './Settings'
export { IconUser } from './User'
export { IconOnlineStore } from './OnlineStore'
export { IconShipping } from './Shipping'
export { IconLogout } from './Logout'
export { IconKeys } from './Keys'
export { IconGlobe } from './Globe'
export { IconCustomers } from './Customers'
export { IconProducts } from './Products'
export { IconRocket } from './Rocket'
export { IconFlag } from './Flag'
export { IconBook } from './Book'
export { IconCode } from './Code'
export { IconHeartbeat } from './Heartbeat'
export { IconDocument } from './Document'
export { IconSupport } from './Support'
