import { createPlugin } from '../system'

export const borders = createPlugin({
  name: 'onda-plugin-borders',
  namespaces: [
    'border',
    'borders',
    'borderWidths',
    'borderStyles',
    'borderRadius',
  ],
  rules: {
    border: 'border',
    borderTop: 'borders',
    borderRight: 'borders',
    borderBottom: 'borders',
    borderLeft: 'borders',
    borderWidth: 'borderWidths',
    borderStyle: 'borderStyles',
    borderRadius: 'borderRadius',
    borderTopRightRadius: 'borderRadius',
    borderTopLeftRadius: 'borderRadius',
    borderBottomRightRadius: 'borderRadius',
    borderBottomLeftRadius: 'borderRadius',
    borderTopWidth: 'borderWidths',
    borderTopStyle: 'borderStyles',
    borderBottomWidth: 'borderWidths',
    borderBottomStyle: 'borderStyles',
    borderLeftWidth: 'borderWidths',
    borderLeftStyle: 'borderStyles',
    borderRightWidth: 'borderWidths',
    borderRightStyle: 'borderStyles',
    borderBlock: 'borders',
    borderBlockEnd: 'borders',
    borderBlockEndStyle: 'borderStyles',
    borderBlockEndWidth: 'borderWidths',
    borderBlockStart: 'borders',
    borderBlockStartStyle: 'borderStyles',
    borderBlockStartWidth: 'borderWidths',
    borderBlockStyle: 'borderStyles',
    borderBlockWidth: 'borderWidths',
    borderEndEndRadius: 'borderRadius',
    borderEndStartRadius: 'borderRadius',
    borderInline: 'borders',
    borderInlineEnd: 'borders',
    borderInlineEndStyle: 'borderStyles',
    borderInlineEndWidth: 'borderWidths',
    borderInlineStart: 'borders',
    borderInlineStartStyle: 'borderStyles',
    borderInlineStartWidth: 'borderWidths',
    borderInlineStyle: 'borderStyles',
    borderInlineWidth: 'borderWidths',
    borderStartEndRadius: 'borderRadius',
    borderStartStartRadius: 'borderRadius',
  },
})
