export const theme = {
  '$breakpoint-small': '48rem',
  '$breakpoint-medium': '64rem',
  '$breakpoint-large': '90rem',
  '$space-0': '0rem',
  '$space-1': '0.25rem',
  '$space-2': '0.5rem',
  '$space-3': '0.75rem',
  '$space-4': '1rem',
  '$space-5': '1.25rem',
  '$space-6': '1.5rem',
  '$space-7': '1.75rem',
  '$space-8': '2rem',
  '$space-10': '2.5rem',
  '$space-12': '3rem',
  '$space-16': '4rem',
  '$space-20': '5rem',
  '$space-24': '6rem',
  '$space-28': '7rem',
  '$space-32': '8rem',
  '$space-05': '0.125rem',
  '$color-transparent': 'transparent',
  '$color-gray-0': '#FFFFFF',
  '$color-gray-1': '#F5F5F5',
  '$color-gray-2': '#EDEDED',
  '$color-gray-3': '#E6E6E6',
  '$color-gray-4': '#DEDEDE',
  '$color-gray-5': '#C7C7C7',
  '$color-gray-6': '#B1B1B1',
  '$color-gray-7': '#9B9B9B',
  '$color-gray-8': '#868686',
  '$color-gray-9': '#717171',
  '$color-gray-10': '#666666',
  '$color-gray-11': '#5B5B5B',
  '$color-gray-12': '#484848',
  '$color-gray-13': '#303030',
  '$color-gray-14': '#1D1D1D',
  '$color-red-1': '#FAEFED',
  '$color-red-2': '#FDE8E3',
  '$color-red-3': '#FFDDD6',
  '$color-red-4': '#FFD2C9',
  '$color-red-5': '#F7B5A7',
  '$color-red-6': '#EC9887',
  '$color-red-7': '#DF7B67',
  '$color-red-8': '#D45B45',
  '$color-red-9': '#CA3A22',
  '$color-red-10': '#BA2205',
  '$color-red-11': '#A81B00',
  '$color-red-12': '#861502',
  '$color-red-13': '#5A1207',
  '$color-orange-1': '#FCF3ED',
  '$color-orange-2': '#F9EADD',
  '$color-orange-3': '#FBE1CC',
  '$color-orange-4': '#FBD6B9',
  '$color-orange-5': '#F3C197',
  '$color-orange-6': '#E6A66F',
  '$color-orange-7': '#DF914B',
  '$color-orange-8': '#DC7E0E',
  '$color-orange-9': '#C87000',
  '$color-orange-10': '#B56500',
  '$color-orange-11': '#A35900',
  '$color-orange-12': '#834600',
  '$color-orange-13': '#5B3000',
  '$color-green-1': '#F2F6F1',
  '$color-green-2': '#E7F1E4',
  '$color-green-3': '#DBECD5',
  '$color-green-4': '#CFE7C4',
  '$color-green-5': '#B2D3A4',
  '$color-green-6': '#98BF83',
  '$color-green-7': '#7DAB64',
  '$color-green-8': '#62973B',
  '$color-green-9': '#488409',
  '$color-green-10': '#3F7700',
  '$color-green-11': '#386A00',
  '$color-green-12': '#2E5304',
  '$color-green-13': '#1D3900',
  '$color-teal-1': '#ECF8F6',
  '$color-teal-2': '#ECF8F7',
  '$color-teal-3': '#ECF8F8',
  '$color-teal-4': '#ECF8F9',
  '$color-teal-5': '#ECF8F10',
  '$color-teal-6': '#ECF8F11',
  '$color-teal-7': '#ECF8F12',
  '$color-teal-8': '#ECF8F13',
  '$color-teal-9': '#ECF8F14',
  '$color-teal-10': '#ECF8F15',
  '$color-teal-11': '#ECF8F16',
  '$color-teal-12': '#ECF8F17',
  '$color-teal-13': '#ECF8F18',
  '$color-blue-1': '#F1F5FD',
  '$color-blue-2': '#E4EEFE',
  '$color-blue-3': '#D9E7FF',
  '$color-blue-4': '#CAE0FF',
  '$color-blue-5': '#A8C9FB',
  '$color-blue-6': '#86B3F3',
  '$color-blue-7': '#669CEA',
  '$color-blue-8': '#3F86E2',
  '$color-blue-9': '#096ED9',
  '$color-blue-10': '#0064C3',
  '$color-blue-11': '#0959AC',
  '$color-blue-12': '#00478A',
  '$color-blue-13': '#003060',
  '$color-purple-1': '#F7F3FC',
  '$color-purple-2': '#EFEAFB',
  '$color-purple-3': '#E9E1FE',
  '$color-purple-4': '#E1D7FF',
  '$color-purple-5': '#CBBDF7',
  '$color-purple-6': '#B6A4EC',
  '$color-purple-7': '#A18AE2',
  '$color-purple-8': '#8D70D9',
  '$color-purple-9': '#7B53D1',
  '$color-purple-10': '#6F45C6',
  '$color-purple-11': '#633CB4',
  '$color-purple-12': '#4D2D94',
  '$color-purple-13': '#351B6B',
  '$color-pink-1': '#FCF2F5',
  '$color-pink-2': '#FCE7ED',
  '$color-pink-3': '#FFDBE8',
  '$color-pink-4': '#FFCEE3',
  '$color-pink-5': '#F4B0CE',
  '$color-pink-6': '#E693BC',
  '$color-pink-7': '#DA74A9',
  '$color-pink-8': '#CC5498',
  '$color-pink-9': '#BE2B86',
  '$color-pink-10': '#B20C7D',
  '$color-pink-11': '#A10070',
  '$color-pink-12': '#80005C',
  '$color-pink-13': '#59003F',
  '$color-cyan-1': '#EDF7FA',
  '$color-cyan-2': '#DDF2F9',
  '$color-cyan-3': '#CCEDF6',
  '$color-cyan-4': '#BAE7F3',
  '$color-cyan-5': '#89D5E8',
  '$color-cyan-6': '#55C2DA',
  '$color-cyan-7': '#00ADCA',
  '$color-cyan-8': '#0096AE',
  '$color-cyan-9': '#007F94',
  '$color-cyan-10': '#007385',
  '$color-cyan-11': '#006775',
  '$color-cyan-12': '#00525E',
  '$color-cyan-13': '#003740',
  '$color-fg': 'var(--sl-color-gray-14)',
  '$color-fg-disabled': 'var(--sl-color-gray-7)',
  '$color-fg-inverted': 'var(--sl-color-gray-0)',
  '$color-fg-warning': 'var(--sl-color-orange-9)',
  '$color-fg-success': 'var(--sl-color-green-9)',
  '$color-fg-informational': 'var(--sl-color-cyan-9)',
  '$color-fg-muted': 'var(--sl-color-gray-10)',
  '$color-fg-muted-hover': 'var(--sl-color-gray-11)',
  '$color-fg-muted-pressed': 'var(--sl-color-gray-12)',
  '$color-fg-accent': 'var(--sl-color-blue-10)',
  '$color-fg-accent-hover': 'var(--sl-color-blue-11)',
  '$color-fg-accent-pressed': 'var(--sl-color-blue-12)',
  '$color-fg-critical': 'var(--sl-color-red-9)',
  '$color-fg-critical-hover': 'var(--sl-color-red-10)',
  '$color-fg-critical-pressed': 'var(--sl-color-red-11)',
  '$color-bg': 'var(--sl-color-gray-0)',
  '$color-bg-disabled':
    'color-mix(in srgb, var(--sl-color-gray-14) 5%, transparent)',
  '$color-bg-warning': 'var(--sl-color-orange-2)',
  '$color-bg-success': 'var(--sl-color-green-2)',
  '$color-bg-informational': 'var(--sl-color-cyan-2)',
  '$color-bg-strong': '#color-gray-3',
  '$color-bg-strong-disabled': '#color-gray-6',
  '$color-bg-inverted': 'var(--sl-color-gray-14)',
  '$color-bg-inverted-transparent':
    'color-mix(in srgb, var(--sl-color-gray-14) 50%, transparent)',
  '$color-bg-muted': 'var(--sl-color-gray-1)',
  '$color-bg-muted-hover': 'var(--sl-color-gray-2)',
  '$color-bg-muted-pressed': 'var(--sl-color-gray-3)',
  '$color-bg-muted-transparent':
    'color-mix(in srgb, var(--sl-color-gray-14) 0%, transparent)',
  '$color-bg-muted-transparent-hover':
    'color-mix(in srgb, var(--sl-color-gray-14) 5%, transparent)',
  '$color-bg-muted-transparent-pressed':
    'color-mix(in srgb, var(--sl-color-gray-14) 10%, transparent)',
  '$color-bg-accent': 'var(--sl-color-blue-2)',
  '$color-bg-accent-hover': 'var(--sl-color-blue-3)',
  '$color-bg-accent-pressed': 'var(--sl-color-blue-4)',
  '$color-bg-accent-transparent':
    'color-mix(in srgb, var(--sl-color-blue-10) 0%, transparent)',
  '$color-bg-accent-transparent-hover':
    'color-mix(in srgb, var(--sl-color-blue-10) 5%, transparent)',
  '$color-bg-accent-transparent-pressed':
    'color-mix(in srgb, var(--sl-color-blue-10) 10%, transparent)',
  '$color-bg-accent-strong': 'var(--sl-color-blue-10)',
  '$color-bg-accent-strong-hover': 'var(--sl-color-blue-11)',
  '$color-bg-accent-strong-pressed': 'var(--sl-color-blue-12)',
  '$color-bg-critical': 'var(--sl-color-red-2)',
  '$color-bg-critical-hover': 'var(--sl-color-red-3)',
  '$color-bg-critical-pressed': 'var(--sl-color-red-4)',
  '$color-bg-critical-transparent':
    'color-mix(in srgb, var(--sl-color-red-9) 0%, transparent)',
  '$color-bg-critical-transparent-hover':
    'color-mix(in srgb, var(--sl-color-red-9) 5%, transparent)',
  '$color-bg-critical-transparent-pressed':
    'color-mix(in srgb, var(--sl-color-red-9) 10%, transparent)',
  '$color-bg-critical-strong': 'var(--sl-color-red-9)',
  '$color-bg-critical-strong-hover': 'var(--sl-color-red-10)',
  '$color-bg-critical-strong-pressed': 'var(--sl-color-red-11)',
  $border: '1px solid var(--sl-color-gray-3)',
  '$border-disabled': '1px solid var(--sl-color-gray-6)',
  '$border-success': '1px solid var(--sl-color-green-4)',
  '$border-informational': '1px solid var(--sl-color-cyan-4)',
  '$border-warning': '1px solid var(--sl-color-orange-4)',
  '$border-strong': '1px solid var(--sl-color-gray-5)',
  '$border-strong-hover': '1px solid var(--sl-color-gray-6)',
  '$border-accent': '1px solid var(--sl-color-blue-3)',
  '$border-accent-selected': '1px solid var(--sl-color-blue-10)',
  '$border-critical': '1px solid var(--sl-color-red-4)',
  '$border-critical-strong': '1px solid var(--sl-color-red-8)',
  '$border-critical-strong-hover': '1px solid var(--sl-color-red-9)',
  '$border-radius-none': '0rem',
  '$border-radius-small': '0.25rem',
  '$border-radius-medium': '0.5rem',
  '$border-radius-large': '0.75rem',
  '$border-radius-full': '100%',
  '$focus-ring':
    '0rem 0rem 0rem 0.0625rem var(--sl-color-gray-0,) 0rem 0rem 0rem 0.1875rem var(--sl-color-gray-5)',
  '$focus-ring-critical':
    '0rem 0rem 0rem 0.0625rem var(--sl-color-gray-0,) 0rem 0rem 0rem 0.1875rem var(--sl-color-red-6)',
  '$focus-ring-accent':
    '0rem 0rem 0rem 0.0625rem var(--sl-color-gray-0,) 0rem 0rem 0rem 0.1875rem var(--sl-color-blue-6)',
  '$shadow-1': '0rem 0.125rem 0.5rem 0rem rgba(0, 0, 0, 0.12)',
  '$shadow-2': '0rem 0.25rem 1rem 0rem rgba(0, 0, 0, 0.16)',
  '$shadow-3': '0rem 1.5rem 3rem 0rem rgba(0, 0, 0, 0.16)',
  '$z-1': '0',
  '$z-2': '100',
  '$z-3': '200',
  '$z-4': '300',
  '$z-5': '400',
  '$z-6': '500',
  '$z-7': '600',
  '$z-8': '700',
  '$z-9': '800',
  '$z-10': '900',
  '$font-family-sans':
    '"Inter", -apple-system, system-ui, BlinkMacSystemFont, sans-serif',
  '$font-weight-regular': '400',
  '$font-weight-medium': '500',
  '$font-weight-semibold': '600',
  '$font-size-1': '0.75rem',
  '$font-size-2': '0.875rem',
  '$font-size-3': '1rem',
  '$font-size-4': '1.25rem',
  '$font-size-5': '1.5rem',
  '$letter-spacing-normal': '0em',
  '$letter-spacing-tight': '-0.02em',
  '$letter-spacing-tighter': '-0.04em',
  '$line-height-normal': '1.4',
  '$text-caption-1-font':
    'var(--sl-font-weight-medium) var(--sl-font-size-1) / var(--sl-line-height-normal) var(--sl-font-family-sans)',
  '$text-caption-1-letter-spacing': 'var(--sl-letter-spacing-normal)',
  '$text-caption-2-font':
    'var(--sl-font-weight-regular) var(--sl-font-size-1) / var(--sl-line-height-normal) var(--sl-font-family-sans)',
  '$text-caption-2-letter-spacing': 'var(--sl-letter-spacing-normal)',
  '$text-action-font':
    'var(--sl-font-weight-semibold) var(--sl-font-size-2) / var(--sl-line-height-normal) var(--sl-font-family-sans)',
  '$text-action-letter-spacing': 'var(--sl-letter-spacing-normal)',
  '$text-emphasis-font':
    'var(--sl-font-weight-medium) var(--sl-font-size-2) / var(--sl-line-height-normal) var(--sl-font-family-sans)',
  '$text-emphasis-letter-spacing': 'var(--sl-letter-spacing-normal)',
  '$text-body-font':
    'var(--sl-font-weight-regular) var(--sl-font-size-2) / var(--sl-line-height-normal) var(--sl-font-family-sans)',
  '$text-body-letter-spacing': 'var(--sl-letter-spacing-normal)',
  '$text-display-1-font':
    'var(--sl-font-weight-semibold) var(--sl-font-size-5) / var(--sl-line-height-normal) var(--sl-font-family-sans)',
  '$text-display-1-letter-spacing': 'var(--sl-letter-spacing-tighter)',
  '$text-display-2-font':
    'var(--sl-font-weight-semibold) var(--sl-font-size-4) / var(--sl-line-height-normal) var(--sl-font-family-sans)',
  '$text-display-2-letter-spacing': 'var(--sl-letter-spacing-tighter)',
  '$text-display-3-font':
    'var(--sl-font-weight-semibold) var(--sl-font-size-3) / var(--sl-line-height-normal) var(--sl-font-family-sans)',
  '$text-display-3-letter-spacing': 'var(--sl-letter-spacing-tight)',
  '$text-display-4-font':
    'var(--sl-font-weight-regular) var(--sl-font-size-3) / var(--sl-line-height-normal) var(--sl-font-family-sans)',
  '$text-display-4-letter-spacing': 'var(--sl-letter-spacing-tight)',
}
