export const data = {
  top: [
    {
      icon: 'dashboard',
      label: 'Dashboards',
      englishLabel: 'Dashboards',
      sections: [
        {
          title: null,
          englishTitle: 'Dashboards',
          subItems: [
            {
              label: 'Visão geral',
              englishLabel: 'Overview',
              path: '/admin',
              raccoon: null,
              external: null,
            },
            {
              label: 'Performance de vendas',
              englishLabel: 'Sales Performance',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Performance das páginas web',
              englishLabel: 'Web Page Performance',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
      ],
    },
    {
      icon: 'orders',
      label: 'Pedidos',
      englishLabel: 'Orders',
      sections: [
        {
          title: null,
          englishTitle: 'Orders',
          subItems: [
            {
              label: 'Todos os pedidos',
              englishLabel: 'All Orders',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Transações',
              englishLabel: 'Transactions',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Conciliação bancária',
              englishLabel: 'Bank Reconciliation',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Admin de exemplo',
          englishTitle: 'Example admins',
          subItems: [
            {
              label: '',
              englishLabel: '',
              path: ' /some/path',
              raccoon: {
                prodUrl: 'http://localhost:3000/',
                devUrl: 'http://localhost:3000/',
                __typename: 'Raccoon',
              },
              external: null,
            },
          ],
        },
        {
          title: 'User test cache issue',
          englishTitle: 'User test cache issue',
          subItems: [
            {
              label: 'Vercel',
              englishLabel: 'Vercel',
              path: ' /some/path',
              raccoon: {
                prodUrl: 'https://.app',
                devUrl: null,
                __typename: 'Raccoon',
              },
              external: null,
            },
            {
              label: 'Amplify',
              englishLabel: 'Amplify',
              path: ' /some/path',
              raccoon: {
                prodUrl: '.amplifyap.com',
                devUrl: null,
                __typename: 'Raccoon',
              },
              external: null,
            },
          ],
        },
        {
          title: 'guaxinim foguete',
          englishTitle: 'Rocket Raccoon',
          subItems: [
            {
              label: 'Página principal',
              englishLabel: 'Main Page',
              path: ' /some/path',
              raccoon: {
                prodUrl: '',
                devUrl: null,
                __typename: 'Raccoon',
              },
              external: null,
            },
          ],
        },
      ],
    },
    {
      icon: 'products',
      label: 'Catálogo',
      englishLabel: 'Catalog',
      sections: [
        {
          title: null,
          englishTitle: 'Catalog',
          subItems: [
            {
              label: 'Produtos e SKUs',
              englishLabel: 'Products & Skus',
              path: ' /some/path',
              raccoon: {
                prodUrl: 'https://com/',
                devUrl: null,
                __typename: 'Raccoon',
              },
              external: null,
            },
            {
              label: 'Categorias',
              englishLabel: 'Categories',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Marcas',
              englishLabel: 'Brands',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Coleções',
              englishLabel: 'Collections',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Tipos de lista',
              englishLabel: 'List Types',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Campos personalizados',
              englishLabel: 'Custom Product Attributes',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Importação e exportação',
              englishLabel: 'Import and Export',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Relatórios',
              englishLabel: 'Reports',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Fornecedores',
              englishLabel: 'Suppliers',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Preços',
          englishTitle: 'Prices',
          subItems: [
            {
              label: 'Lista de preços',
              englishLabel: 'Price List',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Regras de preço',
              englishLabel: 'Price Rules',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Estoque',
          englishTitle: 'Inventory',
          subItems: [
            {
              label: 'Gerenciamento de inventário',
              englishLabel: 'Inventory Management',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
      ],
    },
    {
      icon: 'promotions',
      label: 'Promoções',
      englishLabel: 'Promotions',
      sections: [
        {
          title: null,
          englishTitle: 'Promotions',
          subItems: [
            {
              label: 'Promoções',
              englishLabel: 'Promotions',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Audiência de campanhas',
              englishLabel: 'Campaign Audience',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Vales-presente',
              englishLabel: 'Gift Cards',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Taxas',
              englishLabel: 'Taxes',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Cupons',
              englishLabel: 'Coupons',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
      ],
    },
    {
      icon: 'storeFront',
      label: 'Storefront',
      englishLabel: 'Storefront',
      sections: [
        {
          title: null,
          englishTitle: 'Storefront',
          subItems: [
            {
              label: 'Site Editor',
              englishLabel: 'Site Editor',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Layout',
              englishLabel: 'Layout',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Páginas',
              englishLabel: 'Pages',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Estilos',
              englishLabel: 'Styles',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Redirecionamentos',
              englishLabel: 'Redirects',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Mídia',
              englishLabel: 'Media',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Banners',
              englishLabel: 'Banners',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Lançamentos',
          englishTitle: 'Releases',
          subItems: [
            {
              label: 'Calendário',
              englishLabel: 'Calendar',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Lançamentos',
              englishLabel: 'Releases',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Intelligent Search',
          englishTitle: 'Intelligent Search',
          subItems: [
            {
              label: 'Explicação da busca',
              englishLabel: 'Explained Search',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Regras de merchandising',
              englishLabel: 'Merchandising Rules',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Histórico da indexação',
              englishLabel: 'Indexing History',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Regras de relevância',
              englishLabel: 'Relevance Rules',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Analytics',
              englishLabel: 'Analytics',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Redirecionamentos',
              englishLabel: 'Redirects',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Sinônimos',
              englishLabel: 'Synonyms',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
      ],
    },
    {
      icon: 'shipping',
      label: 'Envio',
      englishLabel: 'Shipping',
      sections: [
        {
          title: null,
          englishTitle: 'Shipping',
          subItems: [
            {
              label: 'Estratégia de envio',
              englishLabel: 'Shipping Strategy',
              path: ' /some/path',
              raccoon: {
                prodUrl: 'https://fyapp.com',
                devUrl: 'https://feature-bump-ui.d35se3tvn1e7n0.amplifyapp.com',
                __typename: 'Raccoon',
              },
              external: null,
            },
            {
              label: 'Capacidade de entrega',
              englishLabel: 'Delivery capacity',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Tarifas de envio',
              englishLabel: 'Shipping Rates',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Pontos de retirada',
              englishLabel: 'Pickup Points',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Simulador de envio',
              englishLabel: 'Shipping Simulator',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: null,
          englishTitle: null,
          subItems: [],
        },
      ],
    },
    {
      icon: 'marketplace',
      label: 'Marketplace',
      englishLabel: 'Marketplace',
      sections: [
        {
          title: null,
          englishTitle: 'Marketplace',
          subItems: [
            {
              label: 'Perfil da loja',
              englishLabel: 'Store Profile',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Sellers',
          englishTitle: 'Sellers',
          subItems: [
            {
              label: 'SKUs recebidos',
              englishLabel: 'Received SKUs',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Mapeamento de catálogo',
              englishLabel: 'Catalog Mapping',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Qualidade dos anúncios',
              englishLabel: 'Offer Quality',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Gerenciamento',
              englishLabel: 'Management',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Convite de sellers',
              englishLabel: 'Seller Invite',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Vínculos de SKUs',
              englishLabel: 'SKU Bindings',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Encontrar sellers',
              englishLabel: 'Find Sellers',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Conexões',
          englishTitle: 'Connections',
          subItems: [
            {
              label: 'Pedidos',
              englishLabel: 'Orders',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Produtos',
              englishLabel: 'Products',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Rastreamento',
              englishLabel: 'Tracking',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Preço',
              englishLabel: 'Price',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Estoque',
              englishLabel: 'Inventory',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Gerenciamento de anúncios',
              englishLabel: 'Offer Management',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Marketplaces e integrações',
              englishLabel: 'Marketplaces and Integrations',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
      ],
    },
  ],
  bottom: [
    {
      icon: 'appStore',
      label: 'Aplicativos',
      englishLabel: 'Apps',
      sections: [
        {
          title: 'Hub de Extensões',
          englishTitle: 'Extensions Hub',
          subItems: [
            {
              label: 'App Store',
              englishLabel: 'App Store',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Gerenciamento de Aplicativos',
              englishLabel: 'App Management',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Apps instalados',
          englishTitle: 'Installed Apps',
          subItems: [
            {
              label: 'Chaves de aplicação',
              englishLabel: 'Application Keys',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Audit',
              englishLabel: 'Audit',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Pesquisa de satisfação',
              englishLabel: 'Satisfaction Survey',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Lengow',
              englishLabel: 'Lengow',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Avalara tax calculator',
              englishLabel: 'Avalara tax calculator',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Customer Credit',
          englishTitle: 'Customer Credit',
          subItems: [
            {
              label: 'Títulos',
              englishLabel: 'Invoices',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Contas',
              englishLabel: 'Accounts',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Configurações',
              englishLabel: 'Settings',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'N1 Insight',
          englishTitle: 'N1 Insight',
          subItems: [
            {
              label: 'Overview',
              englishLabel: 'Overview',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Configuração',
              englishLabel: 'Setting',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
      ],
    },
    {
      icon: 'storeSettings',
      label: 'Configurações da loja',
      englishLabel: 'Store Settings',
      sections: [
        {
          title: 'Pagamentos',
          englishTitle: 'Payment',
          subItems: [
            {
              label: 'Configurações',
              englishLabel: 'Settings',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Carteiras digitais',
              englishLabel: 'Digital Wallets',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Pedidos',
          englishTitle: 'Orders',
          subItems: [
            {
              label: 'Configurações',
              englishLabel: 'Settings',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Autorização de pedidos',
              englishLabel: 'Order Authorization',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Templates de email',
          englishTitle: 'Email Templates',
          subItems: [
            {
              label: 'Templates',
              englishLabel: 'Templates',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Remetentes',
              englishLabel: 'Senders',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Envio',
          englishTitle: 'Shipping',
          subItems: [
            {
              label: 'Configurações',
              englishLabel: 'Settings',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Envio por geolocalização',
              englishLabel: 'Geolocation Shipping',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Feriados',
              englishLabel: 'Holidays',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Produtos',
          englishTitle: 'Product',
          subItems: [
            {
              label: 'Condições comerciais',
              englishLabel: 'Commercial Conditions',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Configurações de preços',
              englishLabel: 'Price Settings',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Regras de arredondamento de preços',
              englishLabel: 'Price Rounding Rules',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Storefront',
          englishTitle: 'Storefront',
          subItems: [
            {
              label: 'Configurações',
              englishLabel: 'Settings',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Master Data',
              englishLabel: 'Master Data',
              path: 'http://teamadmin. crm.com.br',
              raccoon: null,
              external: true,
            },
            {
              label: 'Checkout',
              englishLabel: 'Checkout',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Loja',
              englishLabel: 'Store',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'GraphQL IDE',
              englishLabel: 'GraphQL IDE',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Interface personalizada do checkout',
              englishLabel: 'Checkout UI Custom',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Canais',
          englishTitle: 'Channels',
          subItems: [
            {
              label: 'Políticas comerciais',
              englishLabel: 'Trade Policies',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Integração XML',
              englishLabel: 'XML Integration',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
        {
          title: 'Intelligent Search',
          englishTitle: 'Intelligent Search',
          subItems: [
            {
              label: 'Integrações',
              englishLabel: 'Integrations',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
            {
              label: 'Configuração da busca',
              englishLabel: 'Search Settings',
              path: ' /some/path',
              raccoon: null,
              external: null,
            },
          ],
        },
      ],
    },
  ],
}
