export { IconProps, Icon } from '@vtex-components/icon'
export { IconFacebook } from './Facebook'
export { IconInstagram } from './Instagram'
export { IconYouTube } from './YouTube'
export { IconLinkedIn } from './LinkedIn'
export { IconVTEX } from './VTEX'
export { IconVTEXSymbol } from './VTEXSymbol'
export { IconCaret } from './Caret'
export { IconExit } from './Exit'
export { IconHamburger } from './Hamburger'
export { IconVTEXExpanded } from './VTEXExpanded'
export { IconExternalLink } from './ExternalLink'
export { IconMail } from './Mail'
export { IconHelp } from './Help'
