export { ThemeProvider } from './theme'
export { Box, Flex } from 'theme-ui'
export { useTheme, Theme } from '@vtex-components/theme'
export { Button, ButtonProps } from './components/Button'
export { FooterLanding } from './components/FooterLanding'
