import { colors } from '../values'

export const bg = {
  'bg-primary': colors.white,
  'bg-secondary': colors.gray05,
  'bg-disabled': colors.gray10,
  'bg-positive': colors.green10,
  'bg-critical': colors.red10,
  'bg-warning': colors.orange10,
  'bg-info': colors.lightBlue10,
  'bg-inverted': colors.black,
  'bg-overlay': colors.grayTransparent50,
  'bg-skeleton': `linear-gradient(90deg, ${colors.gray10}, ${colors.gray20}), ${colors.gray10}`,
  'bg-action-neutral-secondary': colors.gray05,
  'bg-action-neutral-secondaryHover': colors.gray10,
  'bg-action-neutral-secondaryPressed': colors.gray20,
  'bg-action-neutral-tertiary': 'transparent',
  'bg-action-neutral-tertiaryHover': colors.grayTransparent05,
  'bg-action-neutral-tertiaryPressed': colors.grayTransparent10,
  'bg-action-main-primary': colors.blue40,
  'bg-action-main-primaryHover': colors.blue50,
  'bg-action-main-primaryPressed': colors.blue60,
  'bg-action-main-secondary': colors.blue10,
  'bg-action-main-secondaryHover': colors.blue20,
  'bg-action-main-secondaryPressed': colors.blue30,
  'bg-action-main-tertiary': 'transparent',
  'bg-action-main-tertiaryHover': colors.blue05,
  'bg-action-main-tertiaryPressed': colors.blue10,
  'bg-action-main-tertiarySelected': colors.blue05,
  'bg-action-critical-primary': colors.red40,
  'bg-action-critical-primaryHover': colors.red50,
  'bg-action-critical-primaryPressed': colors.red60,
  'bg-action-critical-secondary': colors.red10,
  'bg-action-critical-secondaryHover': colors.red20,
  'bg-action-critical-secondaryPressed': colors.red30,
  'bg-action-critical-tertiary': 'transparent',
  'bg-action-critical-tertiaryHover': colors.red05,
  'bg-action-critical-tertiaryPressed': colors.red10,
  'bg-action-critical-tertiarySelected': colors.red05,
  'bg-form-neutral': 'transparent',
  'bg-form-neutralHover': colors.gray10,
  'bg-form-neutralPressed': colors.gray30,
  'bg-form-neutralChecked': colors.black,
  'bg-form-neutralCheckedHover': colors.gray60,
  'bg-form-neutralCheckedPressed': colors.gray50,
  'bg-form-neutralInactive': colors.gray30,
  'bg-form-neutralInactiveHover': colors.gray50,
  'bg-form-neutralInactivePressed': colors.gray60,
  'bg-form-neutralActive': colors.black,
  'bg-form-neutralActiveHover': colors.gray60,
  'bg-form-neutralActivePressed': colors.gray50,

  'bg-form-controlHover': 'transparent',
  'bg-form-controlChecked': colors.blue40,
  'bg-form-controlCheckedHover': colors.blue50,
}
