import { border as borderStyles } from '../values'

export const border = {
  'border-neutral': borderStyles('gray20'),
  'border-mainSelected': borderStyles('blue40', 2),
  'border-positive': borderStyles('green30'),
  'border-info': borderStyles('lightBlue30'),
  'border-critical': borderStyles('red30'),
  'border-warning': borderStyles('orange30'),
  'border-disabled': borderStyles('gray40'),
  'border-form-neutral': borderStyles('gray30'),
  'border-form-neutralHover': borderStyles('gray50'),
  'border-form-neutralFocus': borderStyles('gray60'),
  'border-form-neutralPressed': borderStyles('gray60'),
  'border-form-neutralChecked': borderStyles('black'),
  'border-form-neutralCheckedHover': borderStyles('gray60'),
  'border-form-neutralCheckedPressed': borderStyles('gray50'),
  'border-form-critical': borderStyles('red40'),
  'border-form-criticalHover': borderStyles('red50'),
  'border-form-criticalFocus': borderStyles('red60'),
  'border-form-control': borderStyles('gray30'),
  'border-form-controlHover': borderStyles('gray50'),
  'border-form-controlChecked': borderStyles('blue40'),
  'border-form-controlCheckedHover': borderStyles('blue50'),
}
