import { colors } from '../values'

export const fg = {
  'fg-primary': colors.black,
  'fg-secondary': colors.gray50,
  'fg-disabled': colors.gray40,
  'fg-inverted': colors.white,
  'fg-positive': colors.green40,
  'fg-info': colors.lightBlue40,
  'fg-critical': colors.red40,
  'fg-warning': colors.orange40,
  'fg-action-neutral.tertiary': colors.gray50,
  'fg-action-neutral.tertiaryHover': colors.gray60,
  'fg-action-neutral.tertiaryPressed': colors.black,
  'fg-action-main-primary': colors.white,
  'fg-action-main-primaryHover': colors.white,
  'fg-action-main-primaryPressed': colors.white,
  'fg-action-main-secondary': colors.blue40,
  'fg-action-main-secondaryHover': colors.blue50,
  'fg-action-main-secondaryPressed': colors.blue60,
  'fg-action-main-tertiary': colors.blue40,
  'fg-action-main-tertiaryHover': colors.blue50,
  'fg-action-main-tertiaryPressed': colors.blue60,
  'fg-action-main-tertiarySelected': colors.blue40,
  'fg-action-critical-primary': colors.white,
  'fg-action-critical-primaryHover': colors.white,
  'fg-action-critical-primaryPressed': colors.white,
  'fg-action-critical-secondary': colors.red40,
  'fg-action-critical-secondaryHover': colors.red50,
  'fg-action-critical-secondaryPressed': colors.red60,
  'fg-action-critical-tertiary': colors.red40,
  'fg-action-critical-tertiaryHover': colors.red50,
  'fg-action-critical-tertiaryPressed': colors.red60,
  'fg-action-critical-tertiarySelected': colors.red40,

  'fg-form-neutral': colors.black,
  'fg-form-neutralChecked': colors.white,

  'fg-form-controlChecked': colors.white,
}
