export const background = [
  {
    token: 'background.base',
    description: 'Default background color for the whole Admin.',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.muted',
    description: 'Second default background color for the Admin.',
    color: 'grey10',
    type: 'background',
  },
  {
    token: 'background.popup',
    description: 'The background color of Popup component.',
    color: 'black',
    type: 'background',
  },
  {
    token: 'background.popover',
    description: 'The background color of Popover component.',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.modal',
    description: 'The background color of Modal component.',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.overlay',
    description:
      'The color of the mask overlay that appears when you enter a modal state.',
    color: 'greyTransparent50',
    type: 'background',
  },
  {
    token: 'background.container',
    description: 'The background color of Cards.',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.header',
    description: 'Background color of Page Header component.',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.sidebar',
    description: 'Background color of Sidebar component.',
    color: 'grey10',
    type: 'background',
  },
  {
    token: 'background.topbar',
    description: 'Background color of Topbar component.',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.skeleton',
    description: 'Background color of Skeleton component.',
    color: 'grey10',
    type: 'background',
  },
  {
    token: 'background.skeletonMuted',
    description: 'Background color of Skeleton component.',
    color: 'grey20',
    type: 'background',
  },
  {
    token: 'background.action.neutral.ghost',
    description: '-',
    color: 'transparent',
    type: 'background',
  },
  {
    token: 'background.action.neutral.ghostHover',
    description: '-',
    color: 'greyTransparent05',
    type: 'background',
  },
  {
    token: 'background.action.neutral.ghostPressed',
    description: '-',
    color: 'greyTransparent10',
    type: 'background',
  },
  {
    token: 'background.action.neutral.ghostDisabled',
    description: '-',
    color: 'transparent',
    type: 'background',
  },
  {
    token: 'background.action.main.solid',
    description: 'Background color of main solid button.',
    color: 'blue40',
    type: 'background',
  },
  {
    token: 'background.action.main.solidHover',
    description: 'Background color of hover main solid button.',
    color: 'blue50',
    type: 'background',
  },
  {
    token: 'background.action.main.solidPressed',
    description: 'Background color of pressed main solid button.',
    color: 'blue60',
    type: 'background',
  },
  {
    token: 'background.action.main.solidDisabled',
    description: 'Background color of disabled main solid button.',
    color: 'grey30',
    type: 'background',
  },
  {
    token: 'background.action.main.soft',
    description: 'Background color of main soft button',
    color: 'blue10',
    type: 'background',
  },
  {
    token: 'background.action.main.softHover',
    description: 'Background color of hover main soft button.',
    color: 'blue20',
    type: 'background',
  },
  {
    token: 'background.action.main.softPressed',
    description: 'Background color of pressed main soft button.',
    color: 'blue30',
    type: 'background',
  },
  {
    token: 'background.action.main.softDisabled',
    description: 'Background color of disabled main soft button.',
    color: 'grey30',
    type: 'background',
  },
  {
    token: 'background.action.main.text',
    description: 'Background color of main text button.',
    color: 'transparent',
    type: 'background',
  },
  {
    token: 'background.action.main.textHover',
    description: 'Background color of hover main text button.',
    color: 'blue05',
    type: 'background',
  },
  {
    token: 'background.action.main.textPressed',
    description: 'Background color of pressd main text button.',
    color: 'blue10',
    type: 'background',
  },
  {
    token: 'background.action.main.textDisabled',
    description: 'Background color of disabled main text button.',
    color: 'grey30',
    type: 'background',
  },
  {
    token: 'background.action.critical.solid',
    description: 'Background color of critical solid button.',
    color: 'red40',
    type: 'background',
  },
  {
    token: 'background.action.critical.solidHover',
    description: 'Background color of hover critical solid button.',
    color: 'red50',
    type: 'background',
  },
  {
    token: 'background.action.critical.solidPressed',
    description: 'Background color of pressed critical solid button.',
    color: 'red60',
    type: 'background',
  },
  {
    token: 'background.action.critical.solidDisabled',
    description: 'Background color of disabled critical solid button.',
    color: 'grey30',
    type: 'background',
  },
  {
    token: 'background.action.critical.soft',
    description: 'Background color of critical soft button.',
    color: 'red10',
    type: 'background',
  },
  {
    token: 'background.action.critical.softHover',
    description: 'Background color of hover critical soft button.',
    color: 'red20',
    type: 'background',
  },
  {
    token: 'background.action.critical.softPressed',
    description: 'Background color of pressed critical soft button.',
    color: 'red30',
    type: 'background',
  },
  {
    token: 'background.action.critical.softDisabled',
    description: 'Background color of disabled critical soft button.',
    color: 'grey30',
    type: 'background',
  },
  {
    token: 'background.action.critical.text',
    description: 'Background color of critical text button.',
    color: 'transparent',
    type: 'background',
  },
  {
    token: 'background.action.critical.textHover',
    description: 'Background color of hover critical text button.',
    color: 'red05',
    type: 'background',
  },
  {
    token: 'background.action.critical.textPressed',
    description: 'Background color of pressed critical text button.',
    color: 'red10',
    type: 'background',
  },
  {
    token: 'background.action.critical.textDisabled',
    description: 'Background color of disabled critical text button.',
    color: 'grey30',
    type: 'background',
  },
  {
    token: 'background.listBoxItem.main',
    description: '-',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.listBoxItem.mainHover',
    description: '-',
    color: 'blue05',
    type: 'background',
  },
  {
    token: 'background.listBoxItem.mainPressed',
    description: '-',
    color: 'blue10',
    type: 'background',
  },
  {
    token: 'background.listBoxItem.mainSelected',
    description: '-',
    color: 'blue05',
    type: 'background',
  },
  {
    token: 'background.listBoxItem.critical',
    description: '-',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.listBoxItem.criticalHover',
    description: '-',
    color: 'red05',
    type: 'background',
  },
  {
    token: 'background.listBoxItem.criticalPressed',
    description: '-',
    color: 'red10',
    type: 'background',
  },
  {
    token: 'background.listBoxItem.criticalSelected',
    description: '-',
    color: 'red05',
    type: 'background',
  },
  {
    token: 'background.notification.warning',
    description: '-',
    color: 'orange10',
    type: 'background',
  },
  {
    token: 'background.notification.positive',
    description: '-',
    color: 'green10',
    type: 'background',
  },
  {
    token: 'background.notification.info',
    description: '-',
    color: 'lightBlue10',
    type: 'background',
  },
  {
    token: 'background.notification.critical',
    description: '-',
    color: 'red10',
    type: 'background',
  },
  {
    token: 'background.field.neutral',
    description: '-',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.field.neutralHover',
    description: '-',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.field.neutralFocus',
    description: '-',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.field.neutralDisabled',
    description: '-',
    color: 'grey30',
    type: 'background',
  },
  {
    token: 'background.field.critical',
    description: '-',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.field.criticalHover',
    description: '-',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.field.criticalFocus',
    description: '-',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.field.criticalDisabled',
    description: '-',
    color: 'grey30',
    type: 'background',
  },
  {
    token: 'background.control.neutral',
    description: '-',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.control.neutralHover',
    description: '-',
    color: 'grey20',
    type: 'background',
  },
  {
    token: 'background.control.neutralPressed',
    description: '-',
    color: 'grey40',
    type: 'background',
  },
  {
    token: 'background.control.neutralDisabled',
    description: '-',
    color: 'grey30',
    type: 'background',
  },
  {
    token: 'background.control.neutralChecked',
    description: '-',
    color: 'black',
    type: 'background',
  },
  {
    token: 'background.control.neutralCheckedHover',
    description: '-',
    color: 'grey70',
    type: 'background',
  },
  {
    token: 'background.control.neutralCheckedPressed',
    description: '-',
    color: 'grey60',
    type: 'background',
  },
  {
    token: 'background.control.neutralCheckedDisabled',
    description: '-',
    color: 'grey30',
    type: 'background',
  },
  {
    token: 'background.control.neutralIndeterminate',
    description: '-',
    color: 'white',
    type: 'background',
  },
  {
    token: 'background.control.neutralIndeterminateHover',
    description: '-',
    color: 'grey20',
    type: 'background',
  },
  {
    token: 'background.control.neutralIndeterminatePressed',
    description: '-',
    color: 'grey40',
    type: 'background',
  },
  {
    token: 'background.control.neutralIndeterminateDisabled',
    description: '-',
    color: 'grey30',
    type: 'background',
  },
]

export const foreground = [
  {
    token: 'foreground.base',
    description: 'Color for main text.',
    color: 'black',
    type: 'foreground',
  },
  {
    token: 'foreground.muted',
    description: 'Color for secondary text and icons.',
    color: 'grey50',
    type: 'foreground',
  },
  {
    token: 'foreground.highlight',
    description: 'Color for highlight texts or numbers.',
    color: 'lightBlue40',
    type: 'foreground',
  },
  {
    token: 'foreground.popup',
    description: '-',
    color: 'white',
    type: 'foreground',
  },
  {
    token: 'foreground.popover',
    description: '-',
    color: 'black',
    type: 'foreground',
  },
  {
    token: 'foreground.modal',
    description: '-',
    color: 'black',
    type: 'foreground',
  },
  {
    token: 'foreground.container',
    description: '-',
    color: 'black',
    type: 'foreground',
  },
  {
    token: 'foreground.header',
    description: '-',
    color: 'black',
    type: 'foreground',
  },
  {
    token: 'foreground.sidebar',
    description: '-',
    color: 'grey50',
    type: 'foreground',
  },
  {
    token: 'foreground.topbar',
    description: '-',
    color: 'grey50',
    type: 'foreground',
  },
  {
    token: 'foreground.action.neutral.ghost',
    description: '-',
    color: 'black',
    type: 'foreground',
  },
  {
    token: 'foreground.action.neutral.ghostDisabled',
    description: '-',
    color: 'grey40',
    type: 'foreground',
  },
  {
    token: 'foreground.action.main.solid',
    description: '-',
    color: 'white',
    type: 'foreground',
  },
  {
    token: 'foreground.action.main.solidDisabled',
    description: '-',
    color: 'grey50',
    type: 'foreground',
  },
  {
    token: 'foreground.action.main.soft',
    description: '-',
    color: 'blue40',
    type: 'foreground',
  },
  {
    token: 'foreground.action.main.softDisabled',
    description: '-',
    color: 'grey50',
    type: 'foreground',
  },
  {
    token: 'foreground.action.main.text',
    description: '-',
    color: 'blue40',
    type: 'foreground',
  },
  {
    token: 'foreground.action.main.textDisabled',
    description: '-',
    color: 'grey40',
    type: 'foreground',
  },
  {
    token: 'foreground.action.critical.solid',
    description: '-',
    color: 'white',
    type: 'foreground',
  },
  {
    token: 'foreground.action.critical.solidDisabled',
    description: '-',
    color: 'grey50',
    type: 'foreground',
  },
  {
    token: 'foreground.action.critical.soft',
    description: '-',
    color: 'red50',
    type: 'foreground',
  },
  {
    token: 'foreground.action.critical.softDisabled',
    description: '-',
    color: 'grey50',
    type: 'foreground',
  },
  {
    token: 'foreground.action.critical.text',
    description: '-',
    color: 'red40',
    type: 'foreground',
  },
  {
    token: 'foreground.action.critical.textDisabled',
    description: '-',
    color: 'grey40',
    type: 'foreground',
  },
  {
    token: 'foreground.listBoxItem.main',
    description: '-',
    color: 'black',
    type: 'foreground',
  },
  {
    token: 'foreground.listBoxItem.mainHover',
    description: '-',
    color: 'blue50',
    type: 'foreground',
  },
  {
    token: 'foreground.listBoxItem.mainPressed',
    description: '-',
    color: 'blue60',
    type: 'foreground',
  },
  {
    token: 'foreground.listBoxItem.mainSelected',
    description: '-',
    color: 'blue40',
    type: 'foreground',
  },
  {
    token: 'foreground.listBoxItem.critical',
    description: '-',
    color: 'black',
    type: 'foreground',
  },
  {
    token: 'foreground.listBoxItem.criticalHover',
    description: '-',
    color: 'red40',
    type: 'foreground',
  },
  {
    token: 'foreground.listBoxItem.criticalPressed',
    description: '-',
    color: 'red50',
    type: 'foreground',
  },
  {
    token: 'foreground.listBoxItem.criticalSelected',
    description: '-',
    color: 'red60',
    type: 'foreground',
  },
  {
    token: 'foreground.link',
    description: 'Active link text.',
    color: 'blue40',
    type: 'foreground',
  },
  {
    token: 'foreground.linkHover',
    description: 'Hover link text.',
    color: 'blue50',
    type: 'foreground',
  },
  {
    token: 'foreground.linkVisited',
    description: 'Visited link text.',
    color: 'blue60',
    type: 'foreground',
  },
  {
    token: 'foreground.notification.positive',
    description: 'Icon color for positive message on Toast.',
    color: 'green40',
    type: 'foreground',
  },
  {
    token: 'foreground.notification.info',
    description: 'Icon color for information message on Toast.',
    color: 'lightBlue40',
    type: 'foreground',
  },
  {
    token: 'foreground.notification.critical',
    description: 'Icon color for critical message on Toast.',
    color: 'red40',
    type: 'foreground',
  },
  {
    token: 'foreground.notification.warning',
    description: 'Icon color for warning message on Toast.',
    color: 'orange40',
    type: 'foreground',
  },
  {
    token: 'foreground.control.neutral',
    description: 'Color for default control elements.',
    color: 'white',
    type: 'foreground',
  },
  {
    token: 'foreground.control.neutralDisabled',
    description: 'Color for disabled control elements.',
    color: 'grey50',
    type: 'foreground',
  },
  {
    token: 'foreground.control.neutralChecked',
    description: 'Color for checked control elements.',
    color: 'white',
    type: 'foreground',
  },
  {
    token: 'foreground.control.neutralCheckedDisabled',
    description: 'Color for checked disabled control elements.',
    color: 'grey50',
    type: 'foreground',
  },
  {
    token: 'foreground.control.neutralIndeterminate',
    description: 'Color for indeterminate control elements.',
    color: 'grey60',
    type: 'foreground',
  },
  {
    token: 'foreground.control.neutralIndeterminateDisabled',
    description: 'Color for indeterminate disableds control elements.',
    color: 'grey50',
    type: 'foreground',
  },
]

export const borderColor = [
  {
    token: 'borderColor.base',
    description: 'Default border color for UI elements.',
    color: 'grey30',
    type: 'borderColor',
  },
  {
    token: 'borderColor.popover',
    description: 'Border color for Popover component.',
    color: 'grey30',
    type: 'borderColor',
  },
  {
    token: 'borderColor.modal',
    description: 'Border color for Modal component.',
    color: 'grey30',
    type: 'borderColor',
  },
  {
    token: 'borderColor.container',
    description: 'Border color for Cards component.',
    color: 'grey30',
    type: 'borderColor',
  },
  {
    token: 'borderColor.header',
    description: 'Border color for Page Header component.',
    color: 'grey30',
    type: 'borderColor',
  },
  {
    token: 'borderColor.sidebar',
    description: 'Border color for Sidebar component.',
    color: 'grey30',
    type: 'borderColor',
  },
  {
    token: 'borderColor.topbar',
    description: 'Border color for Topbar component.',
    color: 'grey30',
    type: 'borderColor',
  },
  {
    token: 'borderColor.field.neutral',
    description: 'Border color default on form elements.',
    color: 'grey40',
    type: 'borderColor',
  },
  {
    token: 'borderColor.field.neutralHover',
    description: 'Border color default on hover form elements.',
    color: 'grey50',
    type: 'borderColor',
  },
  {
    token: 'borderColor.field.neutralFocus',
    description: 'Border color default on focus form elements.',
    color: 'grey60',
    type: 'borderColor',
  },
  {
    token: 'borderColor.field.neutralDisabled',
    description: 'Border color default on disabled form elements.',
    color: 'grey50',
    type: 'borderColor',
  },
  {
    token: 'borderColor.field.critical',
    description: 'Border color critical on form elements.',
    color: 'red40',
    type: 'borderColor',
  },
  {
    token: 'borderColor.field.criticalHover',
    description: 'Border color critical on form elements.',
    color: 'red50',
    type: 'borderColor',
  },
  {
    token: 'borderColor.field.criticalFocus',
    description: 'Border color critical on focus form elements.',
    color: 'red60',
    type: 'borderColor',
  },
  {
    token: 'borderColor.field.criticalDisabled',
    description: 'Border color on critical on disabled form elements.',
    color: 'grey50',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutral',
    description: '-',
    color: 'grey40',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutralHover',
    description: '-',
    color: 'grey70',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutralPressed',
    description: '-',
    color: 'grey60',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutralDisabled',
    description: '-',
    color: 'grey50',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutralChecked',
    description: '-',
    color: 'black',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutralCheckedHover',
    description: '-',
    color: 'grey70',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutralCheckedPressed',
    description: '-',
    color: 'grey60',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutralCheckedDisabled',
    description: '-',
    color: 'grey50',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutralIndeterminate',
    description: '-',
    color: 'grey40',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutralIndeterminateHover',
    description: '-',
    color: 'grey70',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutralIndeterminatePressed',
    description: '-',
    color: 'grey60',
    type: 'borderColor',
  },
  {
    token: 'borderColor.control.neutralIndeterminateDisabled',
    description: '-',
    color: 'grey50',
    type: 'borderColor',
  },
  {
    token: 'borderColor.notification.positive',
    description: '-',
    color: 'green30',
    type: 'borderColor',
  },
  {
    token: 'borderColor.notification.info',
    description: '-',
    color: 'lightBlue30',
    type: 'borderColor',
  },
  {
    token: 'borderColor.notification.critical',
    description: '-',
    color: 'red30',
    type: 'borderColor',
  },
  {
    token: 'borderColor.notification.warning',
    description: '-',
    color: 'orange30',
    type: 'borderColor',
  },
]

export const shadows = [
  {
    token: 'shadows.ring.critical',
    description: '-',
    color: '0rem 0rem 0rem 0.125rem {colors.red20}',
    type: 'shadows',
  },
  {
    token: 'shadows.ring.warning',
    description: '-',
    color: '0rem 0rem 0rem 0.125rem {colors.orange20}',
    type: 'shadows',
  },
  {
    token: 'shadows.ring.positive',
    description: '-',
    color: '0rem 0rem 0rem 0.125rem {colors.green20}',
    type: 'shadows',
  },
  {
    token: 'shadows.ring.neutral',
    description: '-',
    color: '0rem 0rem 0rem 0.125rem {colors.grey20}',
    type: 'shadows',
  },
  {
    token: 'shadows.ring.info',
    description: '-',
    color: '0rem 0rem 0rem 0.125rem {colors.lightBlue20}',
    type: 'shadows',
  },
  {
    token: 'shadows.ring.main',
    description: '-',
    color: '0rem 0rem 0rem 0.125rem {colors.blue20}',
    type: 'shadows',
  },
  {
    token: 'shadows.menu',
    description: '-',
    color: '0rem 0rem 1rem 0rem rgba(0,0,0,0.10)',
    type: 'shadows',
  },
  {
    token: 'shadows.subtle',
    description: '-',
    color: '0rem 0rem 1.5rem 0rem rgba(0,0,0,0.05)',
    type: 'shadows',
  },
]

export const tokens = [...background, ...foreground, ...borderColor, ...shadows]
