import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Tabs, Tab, TabList, TabPanel } from '@vtex/shoreline-layouts'
import '@vtex/shoreline-components/styles'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  // children,
  tabs,
}: {
  children: React.ReactNode
  tabs: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Tabs>
          <TabList>
            <Tab href="/">Hot</Tab>
            <Tab href="/new">New</Tab>
          </TabList>
          <TabPanel>{tabs}</TabPanel>
        </Tabs>
      </body>
    </html>
  )
}
